services:
  postgresql:
    container_name: postgresql${ENVIRONMENT_SUFFIX:-}
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      - xians-community-edition
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ../keycloak/init-keycloak-db.sql:/docker-entrypoint-initdb.d/01-init-keycloak-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  xians-community-edition:
    external: true
    name: xians-community-edition-network${ENVIRONMENT_SUFFIX:-}

volumes:
  postgresql_data:
    name: postgresql-data${ENVIRONMENT_SUFFIX:-}
    driver: local 