# This is the docker-compose.yml file for the Xians Community Edition.
# V1.0.1

services:
  xiansai-server:
    image: 99xio/xiansai-server:latest
    container_name: xians-server
    restart: unless-stopped
    ports:
      - "5001:80"
    env_file:
      - server/.env.development
    networks:
      - xians-community-edition
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  xiansai-ui:
    image: 99xio/xiansai-ui:latest
    container_name: xians-ui
    restart: unless-stopped
    ports:
      - "3001:80"
    env_file:
      - ui/.env.development
    networks:
      - xians-community-edition
    depends_on:
      xiansai-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  xians-community-edition:
    driver: bridge
    name: xians-community-edition-network

volumes:
  xiansai-data:
    name: xians-community-edition-data 