version: '3.8'

services:
  xiansai-server:
    image: xiansai/server:latest
    container_name: xians-server
    restart: unless-stopped
    ports:
      - "5000:8080"
    env_file:
      - server/.env.development
    networks:
      - xians
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  xiansai-ui:
    image: xiansai/ui:latest
    container_name: xians-ui
    restart: unless-stopped
    ports:
      - "3000:80"
    env_file:
      - ui/.env.development
    networks:
      - xians
    depends_on:
      xiansai-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  xians:
    driver: bridge
    name: xians-network

volumes:
  xiansai-data:
    name: xians-data 