# XiansAi Community Edition - Unified Docker Compose
# Supports both development and production environments
# Set ENVIRONMENT=production for production mode

services:
  mongodb:
    image: mongo:latest
    container_name: xians-mongodb${ENVIRONMENT_SUFFIX:-}
    restart: unless-stopped
    command: bash /mongo-startup.sh
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ${MONGO_SCRIPT_PATH:-./db/mongo-healthcheck.js}:${MONGO_SCRIPT_MOUNT:-/mongo-healthcheck.js}:ro
      - ./db/mongo-startup.sh:/mongo-startup.sh:ro
    networks:
      - xians-community-edition
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "rs.status().members[0].stateStr" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: ${MONGO_MEMORY_LIMIT:-512M}
        reservations:
          memory: ${MONGO_MEMORY_RESERVATION:-256M}
    logging:
      driver: ${LOGGING_DRIVER:-local}
      options:
        max-size: ${LOG_MAX_SIZE:-50m}
        max-file: ${LOG_MAX_FILE:-2}

  xiansai-server:
    image: ${SERVER_IMAGE:-99xio/xiansai-server:latest}
    container_name: xians-server${ENVIRONMENT_SUFFIX:-}
    restart: unless-stopped
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENV:-Development}
    env_file:
      - server/.env.${ENVIRONMENT:-local}
    networks:
      - xians-community-edition
    volumes:
      - xiansai-data:/app/data
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: ${SERVER_MEMORY_LIMIT:-1G}
        reservations:
          memory: ${SERVER_MEMORY_RESERVATION:-512M}
    logging:
      driver: ${LOGGING_DRIVER:-local}
      options:
        max-size: ${LOG_MAX_SIZE:-50m}
        max-file: ${LOG_MAX_FILE:-2}

  xiansai-ui:
    image: ${UI_IMAGE:-99xio/xiansai-ui:latest}
    container_name: xians-ui${ENVIRONMENT_SUFFIX:-}
    restart: unless-stopped
    ports:
      - "3001:80"
    env_file:
      - ui/.env.${ENVIRONMENT:-development}
    networks:
      - xians-community-edition
    depends_on:
      xiansai-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: ${UI_MEMORY_LIMIT:-256M}
        reservations:
          memory: ${UI_MEMORY_RESERVATION:-128M}
    logging:
      driver: ${LOGGING_DRIVER:-local}
      options:
        max-size: ${LOG_MAX_SIZE:-50m}
        max-file: ${LOG_MAX_FILE:-2}



networks:
  xians-community-edition:
    driver: bridge
    name: xians-community-edition-network${ENVIRONMENT_SUFFIX:-}

volumes:
  xiansai-data:
    name: xians-community-edition-data${ENVIRONMENT_SUFFIX:-}
    driver: local
  mongodb_data:
    name: xians-mongodb-data${ENVIRONMENT_SUFFIX:-}
    driver: local