services:
  temporal:
    container_name: temporal${ENVIRONMENT_SUFFIX:-}
    external_links:
      - postgresql${ENVIRONMENT_SUFFIX:-}:postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=false
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - xians-community-edition
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  temporal-admin-tools:
    container_name: temporal-admin-tools${ENVIRONMENT_SUFFIX:-}
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    networks:
      - xians-community-edition
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui${ENVIRONMENT_SUFFIX:-}
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - xians-community-edition
    ports:
      - 8080:8080
networks:
  xians-community-edition:
    external: true
    name: xians-community-edition-network${ENVIRONMENT_SUFFIX:-}
